<a href="https://colab.research.google.com/github/DanielFindell/Linear-Algerbra-Projects/blob/main/DeterminantWorkSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [10]:
A = np.matrix([[10, 7], [8, 9]])
B = np.matrix([[-10, -1], [-4, 7]])
C = np.matrix([[1, -3], [7, 7]])
print(A)
print(B)
print(C)

[[10  7]
 [ 8  9]]
[[-10  -1]
 [ -4   7]]
[[ 1 -3]
 [ 7  7]]


In [12]:
print(A*B)
print(B*A)

[[-128   39]
 [-116   55]]
[[-108  -79]
 [  16   35]]


In [14]:
print(np.linalg.det(A*B))
print(np.linalg.det(B*A))

-2515.999999999999
-2516.0000000000014


In [15]:
print(A*C)
print(C*A)

[[59 19]
 [71 39]]
[[-14 -20]
 [126 112]]


In [16]:
print(B*C)
print(C*B)

[[-17  23]
 [ 45  61]]
[[  2 -22]
 [-98  42]]


2).

In [21]:
D = np.matrix([[3, 2, 3], [-6, 1, -10], [-8,-9,-9]])
E = np.matrix([[1, -2, 1], [5, 5, 4], [4, 0, 0]])
F = np.matrix([[1, 0, 0], [0, 2, 0], [-3, -2, 1]])
print(D)
print(E)
print(F)

[[  3   2   3]
 [ -6   1 -10]
 [ -8  -9  -9]]
[[ 1 -2  1]
 [ 5  5  4]
 [ 4  0  0]]
[[ 1  0  0]
 [ 0  2  0]
 [-3 -2  1]]


A).

In [23]:
print(np.linalg.det(D))
print(np.linalg.det(E))
print(np.linalg.det(F))

-58.999999999999964
-51.999999999999986
1.9999999999999998


B).

In [22]:
print(D*E)
print(E*D)
print(np.linalg.det(D*E))
print(np.linalg.det(E*D))

[[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]
[[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]
3067.9999999999973
3067.9999999999973


C).

In [24]:
print(D*F)
print(F*D)
print(np.linalg.det(D*F))
print(np.linalg.det(F*D))

[[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]]
[[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]]
-118.00000000000004
-118.00000000000004


D).

In [25]:
print(E*F)
print(F*E)
print(np.linalg.det(E*F))
print(np.linalg.det(F*E))

[[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]]
[[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]
-103.99999999999999
-104.00000000000007
