<a href="https://colab.research.google.com/github/DanielFindell/Linear-Algerbra-Projects/blob/main/Gram_Schmidt_part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [15]:
r1 = [0, 3, -3, 0]
r2 = [2, 6, -2, 2]
r3 = [-2, 1, -3, 0]
r4 = [2, -4, -2, -4]


In [16]:
n1 = r1

print(np.sqrt(np.dot( n1, n1)))

u1 = n1/np.sqrt(np.dot( n1, n1))
print(u1)

4.242640687119285
[ 0.          0.70710678 -0.70710678  0.        ]


In [17]:
np.dot(u1,u1)

1.0000000000000002

In [18]:
n2 = r2 - np.dot(r2, u1) * u1

print(n2)

print(np.sqrt(np.dot( n2, n2)))

u2 = n2/np.sqrt(np.dot( n2, n2))
print(u2)

[2. 2. 2. 2.]
4.0
[0.5 0.5 0.5 0.5]


In [19]:
print(np.dot(u1,u2))

print(np.dot(u2,u2))

-3.2354269956215097e-16
1.0


In [20]:
n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2

print(n3)

print(np.sqrt(np.dot( n3, n3)))

u3 = n3/np.sqrt(np.dot( n3, n3))
print(u3)

[-1.00000000e+00 -4.44089210e-16  1.33226763e-15  1.00000000e+00]
1.4142135623730951
[-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]


In [21]:
print(np.dot(u1,u3))

print(np.dot(u2,u3))

print(np.dot(u3,u3))

-8.881784197001252e-16
6.106226635438361e-16
0.9999999999999998


In [22]:
n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3

print(n4)

print(np.sqrt(np.dot( n4, n4)))

u4 = n4/np.sqrt(np.dot( n4, n4))
print(u4)

[ 1. -1. -1.  1.]
2.0000000000000004
[ 0.5 -0.5 -0.5  0.5]


In [23]:
print(np.dot(u1,u4))

print(np.dot(u2,u4))

print(np.dot(u3,u4))

print(np.dot(u4,u4))

-2.4257531988555737e-15
1.1657341758564144e-15
5.945620728339695e-17
0.9999999999999999


In [24]:
w = [11, 5, 20, 19]
print(w)


[11, 5, 20, 19]


In [25]:
print(np.dot(u1,w))

print(np.dot(u2,w))

print(np.dot(u3,w))

print(np.dot(u4,w))

-10.606601717798213
27.500000000000004
5.656854249492407
2.5000000000000586
